ethereum_rpc = "https://rpc.hoodi.ethpandaops.io/"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]
[traps.omni_guard]
path = "out/MockOmniGuardTrap.sol/MockOmniGuardTrap.json"
response_contract = "0x11e27724a7A6557f342b7C89d7312634dffBb42f"
response_function = "triggerResponse(string)"
cooldown_period_blocks = 5
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 1
whitelist = ["0xcF75BeA7A11Eb0A764dC85DEf2F36c3ed826aE59"]
private_trap = true
address = "0x1D880D83Ce107C6961495Ef767b8E4099A94F72E"